### ISSUE TITLE
DNSCrypt 2

### ISSUE THREAD

**Issue by What-Zit-Tooya** [cool00geek/dnscrypt-proxy-magisk#1]
I don't know about syntax in version 2, but i think its totally different from version 1 as of discontinued for now.
Update to version 2 would be nice.

**Comment by cool00geek** [comment]
I just updated it! Please try it out and create a new issue if any problems exist.

Download: https://github.com/cool00geek/dnscrypt-proxy-magisk/releases/tag/2.0.11
